"""empty message

Revision ID: 8a70b93b495d
Revises: 
Create Date: 2019-09-19 20:25:12.491440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a70b93b495d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_name', sa.String(length=50), nullable=False),
    sa.Column('char_class', sa.String(length=50), nullable=True),
    sa.Column('item_level', sa.Float(), nullable=True),
    sa.Column('guild', sa.String(length=50), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
